name: test_cicd
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_bloc: ^7.3.0
  bloc: ^7.2.1
  google_fonts: ^2.1.0
  http: ^0.13.3
  equatable: ^2.0.3
  bloc_concurrency: ^0.1.0
  get_it: ^7.2.0
  material_floating_search_bar: ^0.3.4
  fluttertoast: ^8.0.8
  flutter_native_splash: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/porto_logo.png"
  android: true
  ios: true
